/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;
/**
 *
 * @author ziNk
 */
public class VentResumen extends javax.swing.JFrame {

    DefaultTableModel modelo= new DefaultTableModel();
    
    /**
     * Creates new form VentCelular
     */
    public VentResumen() {
        
        initComponents();
        modelo.addColumn("Codigo");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Cant. Dia(s)");
        modelo.addColumn("Precio Base");
        
        this.tblMostrar.setModel(modelo);
    }
    
    public void limpiarTabla()
    {
        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        int n = tblMostrar.getRowCount()-1;
        for (int i = 0; i <=n; i++) {
            dtm.removeRow(dtm.getRowCount()-1);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCelular = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPromDias = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarMarca = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opcIngresar1 = new javax.swing.JMenuItem();
        opcSalir1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opcMostrar1 = new javax.swing.JMenuItem();
        opcResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnCelular.setBackground(new java.awt.Color(0, 102, 102));
        pnCelular.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento (1).png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAN | Tenimiento");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido a MAN|Tenimiento, donde los servicios se realizan por un \"MAN\".");

        tblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Modelo", "Cant. Dia(s)", "PrecioBase"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMostrar);
        if (tblMostrar.getColumnModel().getColumnCount() > 0) {
            tblMostrar.getColumnModel().getColumn(0).setResizable(false);
            tblMostrar.getColumnModel().getColumn(1).setResizable(false);
            tblMostrar.getColumnModel().getColumn(3).setResizable(false);
        }

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnTotal.setText("Total Ingreso(s)");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAN | Productos Resumen");

        btnPromDias.setText("Prom Cant. Dias");
        btnPromDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromDiasActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingrese marca ");

        javax.swing.GroupLayout pnCelularLayout = new javax.swing.GroupLayout(pnCelular);
        pnCelular.setLayout(pnCelularLayout);
        pnCelularLayout.setHorizontalGroup(
            pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnCelularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromDias, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnCelularLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnCelularLayout.setVerticalGroup(
            pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCelularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnPromDias)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBuscarMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnMostrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnLimpiar))
                .addContainerGap())
            .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnCelularLayout.createSequentialGroup()
                    .addGap(0, 313, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 313, Short.MAX_VALUE)))
        );

        jMenu2.setText("MAN |");

        opcIngresar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        opcIngresar1.setText("Ingresar producto");
        opcIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcIngresar1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcIngresar1);

        opcSalir1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        opcSalir1.setText("Salir");
        opcSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalir1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcSalir1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        opcMostrar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        opcMostrar1.setText("Ver Registros");
        opcMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMostrar1ActionPerformed(evt);
            }
        });
        jMenu3.add(opcMostrar1);

        opcResumen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        opcResumen.setText("Ver Resumen");
        opcResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcResumenActionPerformed(evt);
            }
        });
        jMenu3.add(opcResumen);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        limpiarTabla();
        ManDAO man = new ManDAO();
        ArrayList<Producto> prod = man.mostMarcas(txtBuscarMarca.getText());
        if(prod.isEmpty()){
            ArrayList<Producto> p = man.todito();
            DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
            String [][] datos=new String[p.size()][5];
            for (int i = 0; i < p.size(); i++) {
                datos[i][0] = p.get(i).getCodigo();
                datos[i][1] = p.get(i).getMarca();
                datos[i][2] = p.get(i).getModelo();
                datos[i][3] = String.valueOf(p.get(i).getCantDias());
                datos[i][4] = String.valueOf(p.get(i).getPrecioBase());

                dtm.addRow(datos[i]);
            }
            tblMostrar.setModel(dtm);
        }else{
            DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
            String [][] datos=new String[prod.size()][5];
            for (int i = 0; i < prod.size(); i++) {
                datos[i][0] = prod.get(i).getCodigo();
                datos[i][1] = prod.get(i).getMarca();
                datos[i][2] = prod.get(i).getModelo();
                datos[i][3] = String.valueOf(prod.get(i).getCantDias());
                datos[i][4] = String.valueOf(prod.get(i).getPrecioBase());

            dtm.addRow(datos[i]);
            }
            tblMostrar.setModel(dtm);
        } 
     
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        int n=tblMostrar.getRowCount()-1;
        for (int i = 0; i <=n ; i++) {
            dtm.removeRow(dtm.getRowCount()-1);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed

        ManDAO manDAO = new ManDAO();
        JOptionPane.showMessageDialog(this,"Existe un total de " + manDAO.contarProd()+" productos ingresados.");     
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalActionPerformed

    private void opcIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcIngresar1ActionPerformed

        VentIngreso ventIng = new VentIngreso();
        ventIng.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventIng.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventIng.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventIng.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventIng.setVisible(true);//muestra la ventana
    }//GEN-LAST:event_opcIngresar1ActionPerformed

    private void opcSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_opcSalir1ActionPerformed

    private void opcMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMostrar1ActionPerformed

        VentRegistros ventReg = new VentRegistros();
        ventReg.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventReg.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventReg.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventReg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventReg.setVisible(true);//muestra la ventana
        ventReg.setSize(629,315);
    }//GEN-LAST:event_opcMostrar1ActionPerformed

    private void opcResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcResumenActionPerformed
        VentResumen ventEst = new VentResumen();
        ventEst.setLocationRelativeTo(null);
        ventEst.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventEst.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventEst.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventEst.setVisible(true);//muestra la ventana
        ventEst.setSize(680,680); 

        // TODO add your handling code here:
    }//GEN-LAST:event_opcResumenActionPerformed

    private void btnPromDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromDiasActionPerformed

        ManDAO manDAO = new ManDAO();
        JOptionPane.showMessageDialog(this,"El promedio es de " + manDAO.promDias()+ " días");  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromDiasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPromDias;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem opcIngresar1;
    private javax.swing.JMenuItem opcMostrar1;
    private javax.swing.JMenuItem opcResumen;
    private javax.swing.JMenuItem opcSalir1;
    private javax.swing.JPanel pnCelular;
    private javax.swing.JTable tblMostrar;
    private javax.swing.JTextField txtBuscarMarca;
    // End of variables declaration//GEN-END:variables
}
