/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import controlador.ManDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Computador;
/**
 *
 * @author ziNk
 */
public class VentMostrarCompu extends javax.swing.JFrame {

    DefaultTableModel modelo= new DefaultTableModel();
    
    public VentMostrarCompu() {
        
        initComponents();
        modelo.addColumn("Codigo");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("CantDias");
        modelo.addColumn("PrecioBase");
        modelo.addColumn("Limpieza");
        modelo.addColumn("Formateo");
        modelo.addColumn("Cost.Servicio");
        modelo.addColumn("Desc.Ambos");
        modelo.addColumn("TotalPago");
        
        this.tblMostrar.setModel(modelo);
    }
    
    public void limpiarTabla()
    {
        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        int n = tblMostrar.getRowCount()-1;
        for (int i = 0; i <=n; i++) {
            dtm.removeRow(dtm.getRowCount()-1);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMostrar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opcIngresar1 = new javax.swing.JMenuItem();
        opcSalir1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opcMostrar1 = new javax.swing.JMenuItem();
        opcResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnIngreso.setBackground(new java.awt.Color(0, 102, 102));
        pnIngreso.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento (1).png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAN | Tenimiento");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido a MAN|Tenimiento, donde los servicios se realizan por un \"MAN\".");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese Código");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        tblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Modelo", "CantDias", "PrecioBase", "Limpieza", "Formateo", "Cost.Servicio", "Desc.Ambos", "TotalPago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMostrar);
        if (tblMostrar.getColumnModel().getColumnCount() > 0) {
            tblMostrar.getColumnModel().getColumn(0).setResizable(false);
            tblMostrar.getColumnModel().getColumn(1).setResizable(false);
            tblMostrar.getColumnModel().getColumn(2).setResizable(false);
            tblMostrar.getColumnModel().getColumn(3).setResizable(false);
            tblMostrar.getColumnModel().getColumn(4).setResizable(false);
            tblMostrar.getColumnModel().getColumn(5).setResizable(false);
            tblMostrar.getColumnModel().getColumn(6).setResizable(false);
            tblMostrar.getColumnModel().getColumn(7).setResizable(false);
            tblMostrar.getColumnModel().getColumn(8).setResizable(false);
            tblMostrar.getColumnModel().getColumn(9).setResizable(false);
        }

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg (1).png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAN | Computadores");

        btnMostrar1.setText("Total Computadores");
        btnMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnIngresoLayout = new javax.swing.GroupLayout(pnIngreso);
        pnIngreso.setLayout(pnIngresoLayout);
        pnIngresoLayout.setHorizontalGroup(
            pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnIngresoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel5)
                        .addGap(92, 92, 92))
                    .addGroup(pnIngresoLayout.createSequentialGroup()
                        .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnIngresoLayout.createSequentialGroup()
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(251, 251, 251)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnIngresoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(btnMostrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pnIngresoLayout.setVerticalGroup(
            pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnIngresoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnIngresoLayout.createSequentialGroup()
                                .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnMostrar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnLimpiar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        jMenu2.setText("MAN |");

        opcIngresar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        opcIngresar1.setText("Ingresar producto");
        opcIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcIngresar1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcIngresar1);

        opcSalir1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        opcSalir1.setText("Salir");
        opcSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalir1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcSalir1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        opcMostrar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        opcMostrar1.setText("Ver Registros");
        opcMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMostrar1ActionPerformed(evt);
            }
        });
        jMenu3.add(opcMostrar1);

        opcResumen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        opcResumen.setText("Ver Resumen");
        opcResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcResumenActionPerformed(evt);
            }
        });
        jMenu3.add(opcResumen);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        int n=tblMostrar.getRowCount()-1;
        for (int i = 0; i <=n ; i++) {
            dtm.removeRow(dtm.getRowCount()-1);
        }

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        dispose();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
    limpiarTabla();
    ManDAO man = new ManDAO();
    Computador c=man.buscarCompu(txtBuscarCodigo.getText());
    if(c==null){
        ArrayList <Computador> compus = man.obtenerComputadores();
        if(compus.size()==0)
            JOptionPane.showMessageDialog(this,"No hay computadores registrados");
        else{
        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        String [][] datos=new String[compus.size()][10];
        for (int i = 0; i < compus.size(); i++) {
            datos[i][0] = compus.get(i).getCodigo();
            datos[i][1] = compus.get(i).getMarca();
            datos[i][2] = compus.get(i).getModelo();
            datos[i][3] = String.valueOf(compus.get(i).getCantDias());
            datos[i][4] = String.valueOf(compus.get(i).getPrecioBase());
            datos[i][5] = String.valueOf(compus.get(i).isLimpieza());
            datos[i][6] = String.valueOf(compus.get(i).isFormateo());
            datos[i][7] = String.valueOf(compus.get(i).costoServicios());
            datos[i][8] = String.valueOf(compus.get(i).descAmbos());
            datos[i][9] = String.valueOf(compus.get(i).valorFinal());
            
            dtm.addRow(datos[i]);
        }
        tblMostrar.setModel(dtm);
    }
    
    }else{
        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        String [] datos = new String[10];
        datos[0]= c.getCodigo();
        datos[1]= c.getMarca();
        datos[2]= c.getModelo();
        datos[3]= String.valueOf(c.getCantDias());
        datos[4]= String.valueOf(c.getPrecioBase());
        datos[5]= String.valueOf(c.isLimpieza());
        datos[6]= String.valueOf(c.isFormateo());
        datos[7]= String.valueOf(c.costoServicios());
        datos[8]= String.valueOf(c.descAmbos());
        datos[9]= String.valueOf(c.valorFinal());
           
        dtm.addRow(datos);
        tblMostrar.setModel(dtm);
        
    }
    }//GEN-LAST:event_btnMostrarActionPerformed
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        int fila=tblMostrar.getSelectedRow();
        if(fila==-1)
            JOptionPane.showMessageDialog(this, "Debe seleccionar el computador");
        else{
            String codigo=String.valueOf(tblMostrar.getValueAt(fila, 0));
            ManDAO manDAO= new ManDAO();
            manDAO.eliminarComputador(codigo);
            JOptionPane.showMessageDialog(this, "Computador eliminado");
            dtm.removeRow(fila);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
        int fila=tblMostrar.getSelectedRow();
        if(fila==-1)
            JOptionPane.showMessageDialog(this, "Debe seleccionar un celular");
        else{
            String codigo=String.valueOf(tblMostrar.getValueAt(fila,0));
            String marca=String.valueOf(tblMostrar.getValueAt(fila, 1));
            String modelo=String.valueOf(tblMostrar.getValueAt(fila, 2));
            int cantDias=Integer.parseInt(String.valueOf(tblMostrar.getValueAt(fila,3)));
            int precioBase=Integer.parseInt(String.valueOf(tblMostrar.getValueAt(fila,4)));
            boolean limpieza=Boolean.parseBoolean((String)tblMostrar.getValueAt(fila,5));
            boolean formateo=Boolean.parseBoolean((String)tblMostrar.getValueAt(fila, 6));
            Computador compu=new Computador(codigo, marca, modelo, cantDias, precioBase, limpieza, formateo);
            ManDAO manDAO= new ManDAO();
            manDAO.modificarComputador(compu);
            JOptionPane.showMessageDialog(this,"Computador modificado");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar1ActionPerformed

        ManDAO manDAO = new ManDAO();
        JOptionPane.showMessageDialog(this,manDAO.contarCompus()+" Computador(es) Ingresado(s)");        
        
    }//GEN-LAST:event_btnMostrar1ActionPerformed

    private void opcIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcIngresar1ActionPerformed

        VentIngreso ventIng = new VentIngreso();
        ventIng.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventIng.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventIng.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventIng.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventIng.setVisible(true);//muestra la ventana
    }//GEN-LAST:event_opcIngresar1ActionPerformed

    private void opcSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_opcSalir1ActionPerformed

    private void opcMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMostrar1ActionPerformed

        VentRegistros ventReg = new VentRegistros();
        ventReg.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventReg.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventReg.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventReg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventReg.setVisible(true);//muestra la ventana
        ventReg.setSize(629,315);
    }//GEN-LAST:event_opcMostrar1ActionPerformed

    private void opcResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcResumenActionPerformed
        VentResumen ventEst = new VentResumen();
        ventEst.setLocationRelativeTo(null);
        ventEst.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventEst.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventEst.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventEst.setVisible(true);//muestra la ventana
        ventEst.setSize(680,680); 

        // TODO add your handling code here:
    }//GEN-LAST:event_opcResumenActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrar1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem opcIngresar1;
    private javax.swing.JMenuItem opcMostrar1;
    private javax.swing.JMenuItem opcResumen;
    private javax.swing.JMenuItem opcSalir1;
    private javax.swing.JPanel pnIngreso;
    private javax.swing.JTable tblMostrar;
    private javax.swing.JTextField txtBuscarCodigo;
    // End of variables declaration//GEN-END:variables
}
