/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Celular;
import controlador.ManDAO;
/**
 *
 * @author ziNk
 */
public class VentCelular extends javax.swing.JFrame {

    /**
     * Creates new form VentCelular
     */
    public VentCelular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCelular = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ckPantalla = new javax.swing.JCheckBox();
        ckBateria = new javax.swing.JCheckBox();
        ckPlaca = new javax.swing.JCheckBox();
        ckCamara = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        ckImei = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opcIngresar1 = new javax.swing.JMenuItem();
        opcSalir1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opcMostrar1 = new javax.swing.JMenuItem();
        opcResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnCelular.setBackground(new java.awt.Color(0, 102, 102));
        pnCelular.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento (1).png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAN | Tenimiento");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido a MAN|Tenimiento, donde los servicios se realizan por un \"MAN\".");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Desbloqueo");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Remplazar piezas");

        ckPantalla.setText("Pantalla");
        ckPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPantallaActionPerformed(evt);
            }
        });

        ckBateria.setText("Bateria");
        ckBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBateriaActionPerformed(evt);
            }
        });

        ckPlaca.setText("Placa");

        ckCamara.setText("Cámara");
        ckCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckCamaraActionPerformed(evt);
            }
        });

        ckImei.setText("IMEI");
        ckImei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckImeiActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Celular Servicios");

        javax.swing.GroupLayout pnCelularLayout = new javax.swing.GroupLayout(pnCelular);
        pnCelular.setLayout(pnCelularLayout);
        pnCelularLayout.setHorizontalGroup(
            pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnCelularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
            .addGroup(pnCelularLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(ckImei)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                        .addComponent(ckPantalla)
                        .addGap(43, 43, 43)
                        .addComponent(ckBateria)
                        .addGap(38, 38, 38)
                        .addComponent(ckPlaca)
                        .addGap(52, 52, 52)
                        .addComponent(ckCamara)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCelularLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
        );
        pnCelularLayout.setVerticalGroup(
            pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCelularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCelularLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckPantalla)
                    .addComponent(ckBateria)
                    .addComponent(ckPlaca)
                    .addComponent(ckCamara))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(ckImei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(pnCelularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        jMenu2.setText("MAN |");

        opcIngresar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        opcIngresar1.setText("Ingresar producto");
        opcIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcIngresar1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcIngresar1);

        opcSalir1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        opcSalir1.setText("Salir");
        opcSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalir1ActionPerformed(evt);
            }
        });
        jMenu2.add(opcSalir1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        opcMostrar1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        opcMostrar1.setText("Ver Registros");
        opcMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMostrar1ActionPerformed(evt);
            }
        });
        jMenu3.add(opcMostrar1);

        opcResumen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        opcResumen.setText("Ver Resumen");
        opcResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcResumenActionPerformed(evt);
            }
        });
        jMenu3.add(opcResumen);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        dispose();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    
        ckPantalla.setSelected(false);
        ckBateria.setSelected(false);
        ckPlaca.setSelected(false);
        ckCamara.setSelected(false);
        ckImei.setSelected(false);
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        if( ckPantalla.isSelected() ||
            ckBateria.isSelected() ||
            ckPlaca.isSelected() ||
            ckCamara.isSelected() ||
            ckImei.isSelected()){
            
            String codigo,marca,modelo;
            int cantDias,precioBase;
            boolean cPantalla,cBateria,cPlaca,cCamara,cImei;
            Celular celu;
            
            codigo = VentIngreso.txtCodigo.getText();
            marca = VentIngreso.txtMarca.getText();
            modelo = VentIngreso.txtModelo.getText();
            cantDias = Integer.parseInt(VentIngreso.txtDias.getText());
            precioBase = Integer.parseInt(VentIngreso.txtPrecioBase.getText());
            cPantalla = ckPantalla.isSelected();
            cBateria = ckBateria.isSelected();
            cPlaca = ckPlaca.isSelected();
            cCamara = ckCamara.isSelected();
            cImei = ckImei.isSelected();
            
            celu = new Celular(codigo, marca, modelo, cantDias, precioBase, cPantalla, cBateria, cPlaca, cCamara, cImei);
            ManDAO prodDao = new ManDAO();
            if(prodDao.buscarCelu(codigo)==null && codigo.length()<=10 && cantDias<100 && cantDias>0 && precioBase>0){
                prodDao.ingresarCelular(celu);
                JOptionPane.showMessageDialog(this, "Celular Ingresado");
                VentIngreso.txtCodigo.setText(null);
                VentIngreso.txtMarca.setText(null);
                VentIngreso.txtModelo.setText(null);
                VentIngreso.txtDias.setText(null);
                VentIngreso.txtPrecioBase.setText(null);
                ckPantalla.setSelected(false);
                ckBateria.setSelected(false);
                ckPlaca.setSelected(false);
                ckCamara.setSelected(false);
                ckImei.setSelected(false);
                VentIngreso.txtCodigo.requestFocus();
                dispose();
                
            }else if (codigo.length()>10)
                JOptionPane.showMessageDialog(this, "El codigo debe ser menor a 10 digitos");
            else if(cantDias>99 || cantDias<1)
                JOptionPane.showMessageDialog(this, "Rango de Cant.Dias [1,99]");
            else if(precioBase<1)
                JOptionPane.showMessageDialog(this, "Precio Base mayor a 0");
            else{
                JOptionPane.showMessageDialog(this, "Codigo ya existente", 
                    "¡¡ Advertencia !!", JOptionPane.WARNING_MESSAGE);
                VentIngreso.txtCodigo.setText(null);
                VentIngreso.txtMarca.setText(null);
                VentIngreso.txtModelo.setText(null);
                VentIngreso.txtDias.setText(null);
                VentIngreso.txtPrecioBase.setText(null);
                ckPantalla.setSelected(false);
                ckBateria.setSelected(false);
                ckPlaca.setSelected(false);
                ckImei.setSelected(false);
                VentIngreso.txtCodigo.requestFocus();
            }
        }else{
        JOptionPane.showMessageDialog(this,"Seleccione algún servicio");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    private void ckImeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckImeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckImeiActionPerformed

    private void ckCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckCamaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckCamaraActionPerformed

    private void ckBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBateriaActionPerformed

    private void ckPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPantallaActionPerformed

    private void opcIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcIngresar1ActionPerformed

        VentIngreso ventIng = new VentIngreso();
        ventIng.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventIng.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventIng.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventIng.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventIng.setVisible(true);//muestra la ventana

    }//GEN-LAST:event_opcIngresar1ActionPerformed

    private void opcSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_opcSalir1ActionPerformed

    private void opcMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMostrar1ActionPerformed

        VentRegistros ventReg = new VentRegistros();
        ventReg.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventReg.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventReg.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventReg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventReg.setVisible(true);//muestra la ventana
        ventReg.setSize(629,315);

    }//GEN-LAST:event_opcMostrar1ActionPerformed

    private void opcResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcResumenActionPerformed
        VentResumen ventEst = new VentResumen();
        ventEst.setLocationRelativeTo(null);
        ventEst.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventEst.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventEst.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventEst.setVisible(true);//muestra la ventana
        ventEst.setSize(680,680); 

        // TODO add your handling code here:
    }//GEN-LAST:event_opcResumenActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox ckBateria;
    private javax.swing.JCheckBox ckCamara;
    private javax.swing.JCheckBox ckImei;
    private javax.swing.JCheckBox ckPantalla;
    private javax.swing.JCheckBox ckPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem opcIngresar1;
    private javax.swing.JMenuItem opcMostrar1;
    private javax.swing.JMenuItem opcResumen;
    private javax.swing.JMenuItem opcSalir1;
    private javax.swing.JPanel pnCelular;
    // End of variables declaration//GEN-END:variables
}
