/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ziNk
 */
public class VentPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VentPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcIngresar = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcMostrar = new javax.swing.JMenuItem();
        opcResumen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento (2).png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 96)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAN | Tenimiento");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido a MAN|Tenimiento, donde los servicios se realizan por un \"MAN\".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(86, 46));

        jMenu1.setText("MAN |");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        opcIngresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        opcIngresar.setText("Ingresar producto");
        opcIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcIngresarActionPerformed(evt);
            }
        });
        jMenu1.add(opcIngresar);

        opcSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        jMenu1.add(opcSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        opcMostrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        opcMostrar.setText("Ver Registros");
        opcMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMostrarActionPerformed(evt);
            }
        });
        jMenu2.add(opcMostrar);

        opcResumen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        opcResumen.setText("Ver Resumen");
        opcResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcResumenActionPerformed(evt);
            }
        });
        jMenu2.add(opcResumen);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
    dispose();        
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcIngresarActionPerformed
    
        VentIngreso ventIng = new VentIngreso();
        ventIng.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventIng.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventIng.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventIng.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventIng.setVisible(true);//muestra la ventana
       
    }//GEN-LAST:event_opcIngresarActionPerformed

    private void opcMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMostrarActionPerformed

        VentRegistros ventReg = new VentRegistros();
        ventReg.setLocationRelativeTo(null);//muestra la ventana centrada en pantalla
        ventReg.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventReg.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventReg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventReg.setVisible(true);//muestra la ventana
        ventReg.setSize(629,315); 
       
    }//GEN-LAST:event_opcMostrarActionPerformed

    private void opcResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcResumenActionPerformed
        VentResumen ventEst = new VentResumen();
        ventEst.setLocationRelativeTo(null);
        ventEst.setTitle("MAN|Tenimiento");//aquí escribo el título de la ventana
        ventEst.setResizable(false);//se evita que el usuario pueda cambiar el tamaño de la ventana
        ventEst.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita que puedan cerrar la ventana con la X
        ventEst.setVisible(true);//muestra la ventana
        ventEst.setSize(680,680); 


// TODO add your handling code here:
    }//GEN-LAST:event_opcResumenActionPerformed

   ///////////////////////////////////////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem opcIngresar;
    private javax.swing.JMenuItem opcMostrar;
    private javax.swing.JMenuItem opcResumen;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}
